p10/config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :proyects do
    resources :bmcs
    resources :pvs
    resources :tvs
  end

  root 'proyects#index'

end

p10/app/models/tv.rb
class Tv < ActiveRecord::Base
  belongs_to :proyect
end

p10/app/controllers/tvs_controller.rb
class TvsController < ApplicationController
  before_action :set_tv, only: [:show, :edit, :update, :destroy]
  before_action :set_proyect

  # GET /tvs
  # GET /tvs.json
  def index
    @tvs = Tv.where(proyect:@proyect).order(created_at: :desc)
  end

  # GET /tvs/1
  # GET /tvs/1.json
  def show
  end

  # GET /tvs/new
  def new
    @tv = Tv.new
  end

  # GET /tvs/1/edit
  def edit
  end

  # POST /tvs
  # POST /tvs.json
  def create
    @tv = Tv.new(tv_params)
    @tv.proyect = @proyect

    respond_to do |format|
      if @tv.save
        format.html { redirect_to proyect_tv_path(@proyect,@tv), notice: 'Tabla de Valor ha sido creada.' }
        format.json { render :show, status: :created, location: @tv }
      else
        format.html { render :new }
        format.json { render json: @tv.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tvs/1
  # PATCH/PUT /tvs/1.json
  def update
    @tv = Tv.new(tv_params)
    @tv.proyect = @proyect

    respond_to do |format|
      if @tv.update(tv_params)
        format.html { redirect_to proyect_tv_path(@proyect,@tv), notice: 'Tabla de Valor ha sido actualizada.' }
        format.json { render :show, status: :ok, location: @tv }
      else
        format.html { render :edit }
        format.json { render json: @tv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tvs/1
  # DELETE /tvs/1.json
  def destroy
    @tv.destroy
    respond_to do |format|
      format.html { redirect_to proyect_tvs_path(@proyect), notice: 'Tabla de Valor ha sido eliminada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyect
      @proyect = Proyect.find(params[:proyect_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_tv
      @tv = Tv.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tv_params
      params.require(:tv).permit(:hipcli, :hipprob, :hipsol, :invalidamos, :validamos, :proyect_id)
    end
end

p10/app/helpers/tvs_helper.rb
module TvsHelper
end

p10/app/views/tvs/_form.html.erb
<%= form_for([@proyect,@tv]) do |f| %>
  <% if @tv.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tv.errors.count, "error") %> prohibited this tv from being saved:</h2>

      <ul>
      <% @tv.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="field">
    <%= f.label :hipcli, 'Hipotesis del Clientes' %><br>
    <%= f.text_area :hipcli, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :hipprob, 'Hipotesis del Problema' %><br>
    <%= f.text_area :hipprob, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :hipsol, 'Hipotesis de la Solución' %><br>
    <%= f.text_area :hipsol, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :invalidamos, 'Que Invalidamos' %><br>
    <%= f.text_area :invalidamos, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :validamos, 'Que Validamos' %><br>
    <%= f.text_area :validamos, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar', class:"btn btn-info btn-lg" %>
  </div>
</div>
<% end %>

p10/app/views/tvs/edit.html.erb
<h1>Editar Tabla de Validación</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', proyect_tv_path(@proyect,@tv), class:"btn btn-primary pull-left" %>
<%= link_to 'Regresar', proyect_tvs_path(@proyect), class:"btn btn-success pull-right" %>

p10/app/views/tvs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Tabla de Validaciones</h1>

<div class="container">

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr class="info">
      <th>Hipotesis del Cliente</th>
      <th>Hipotesis del Problema</th>
      <th>Hipotesis de la Solución</th>
      <th>Que Invalidamos</th>
      <th>Que Validamos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tvs.each do |tv| %>
      <tr>
        <td><%= tv.hipcli %></td>
        <td><%= tv.hipprob %></td>
        <td><%= tv.hipsol %></td>
        <td><%= tv.invalidamos %></td>
        <td><%= tv.validamos %></td>
        <td><%= link_to 'Mostrar', proyect_tv_path(@proyect,tv) %></td>
        <td><%= link_to 'Editar', edit_proyect_tv_path(@proyect,tv) %></td>
        <td><%= link_to 'Eliminar', [@proyect,tv], method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<br>

<%= link_to 'Nueva Tabla de Validaciones', new_proyect_tv_path(@proyect,@tv), class:"btn btn-primary" %>

<h2>Ver Pvs</h2>
<%= link_to 'Regresar a Propuesta de Valor', proyect_pvs_path(@proyect), class:"btn btn-primary" %>

p10/app/views/tvs/new.html.erb
<h1>Nueva Tabla de Validaciones</h1>

<%= render 'form' %>

<%= link_to 'Regresar', proyect_tvs_path(@proyect), class:"btn btn-success pull-right" %>

p10/app/views/tvs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <strong>Hipotesis del Cliente:</strong>
  <br>
  <div class="container bg-success">
    <%= @tv.hipcli %>
  </div>

  <strong>Hipotesis del Problema:</strong>
  <br>
  <div class="container bg-success">
    <%= @tv.hipprob %>
  </div>

  <strong>Hipotesis de la Solución:</strong>
  <br>
  <div class="container bg-success">
    <%= @tv.hipsol %>
  </div>

  <strong>Que Invalidamos:</strong>
  <br>
  <div class="container bg-success">
    <%= @tv.invalidamos %>
  </div>

  <strong>Que Validamos:</strong>
  <br>
  <div class="container bg-success">
    <%= @tv.validamos %>
  </div>

</div>

<%= link_to 'Editar', edit_proyect_tv_path(@proyect,@tv), class:"btn btn-primary pull-left" %>
<%= link_to 'Regresar', proyect_tvs_path(@proyect), class:"btn btn-success pull-right" %>

<h2>Volver a Proyectos</h2>
<%= link_to 'Regresar a Proyectos', proyects_path, class:"btn btn-primary pull-left" %>