p10/config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :proyects do
    resources :bmcs
    resources :pvs
    resources :tvs
  end

  root 'proyects#index'

end

p10/app/models/proyect.rb
class Proyect < ActiveRecord::Base
  has_many :bmcs, dependent: :destroy
  has_many :pvs, dependent: :destroy
  has_many :tvs, dependent: :destroy
  belongs_to :user

  validates :titulo, :presence => {:message => "Usted debe ingresar un título"}, length: {minimum: 2, maximum: 50, :message => "El título debe tener entre 2 y 50 caracteres"}
  validates :descripcion, :presence => {:message => "Usted debe ingresar una descripción"}, length: {minimum: 2, maximum: 4000, :message => "La descripción debe tener entre 2 y 4000 caracteres"}
end

p10/app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  before_action :set_proyect, only: [:show, :edit, :update, :destroy]

  # GET /proyects
  # GET /proyects.json
  def index
    @proyects = Proyect.where(user_id: current_user.id)
  end

  # GET /proyects/1
  # GET /proyects/1.json
  def show
  end

  # GET /proyects/new
  def new
    @proyect = Proyect.new
  end

  # GET /proyects/1/edit
  def edit
  end

  # POST /proyects
  # POST /proyects.json
  def create
    @proyect = Proyect.new(proyect_params)
    @proyect.user_id = current_user.id

    respond_to do |format|
      if @proyect.save
        format.html { redirect_to @proyect, notice: 'Proyecto ha sido creado.' }
        format.json { render :show, status: :created, location: @proyect }
      else
        format.html { render :new }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyects/1
  # PATCH/PUT /proyects/1.json
  def update
    respond_to do |format|
      if @proyect.update(proyect_params)
        format.html { redirect_to @proyect, notice: 'Proyecto ha sido actuslizado.' }
        format.json { render :show, status: :ok, location: @proyect }
      else
        format.html { render :edit }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyects/1
  # DELETE /proyects/1.json
  def destroy
    @proyect.destroy
    respond_to do |format|
      format.html { redirect_to proyects_url, notice: 'Proyecto ha sido eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyect
      @proyect = Proyect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proyect_params
      params.require(:proyect).permit(:titulo, :descripcion)
    end
end

p10/app/helpers/proyects_helper.rb
module ProyectsHelper
end

p10/app/views/proyects/_form.html.erb
<%= form_for(@proyect) do |f| %>
  <% if @proyect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proyect.errors.count, "error") %> prohibited this proyect from being saved:</h2>

      <ul>
      <% @proyect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar', class:"btn btn-info btn-lg" %>
  </div>
</div>
<% end %>

p10/app/views/proyects/edit.html.erb
<h1>Editar Proyecto</h1>

<% if current_user.id == @proyect.user_id %>

<%= render 'form' %>

<%= link_to 'Mostrar', @proyect, class:"btn btn-primary pull-left" %>
<%= link_to 'Regresar', proyects_path, class:"btn btn-success pull-right" %>

<% else %>

<h2>Acceso Denegado</h2>

<%= link_to 'Regresar', proyects_path, class:"btn btn-success pull-right" %>

<% end %>

p10/app/views/proyects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Proyectos</h1>

<div class="container">

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr class="info">
      <th>Titulo</th>
      <th>Descripción</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proyects.each do |proyect| %>
      <tr>
        <td><%= proyect.titulo %></td>
        <td><%= proyect.descripcion %></td>
        <td><%= link_to 'Mostrar', proyect %></td>
        <td><%= link_to 'Editar', edit_proyect_path(proyect) %></td>
        <td><%= link_to 'Eliminar', proyect, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<br>

<%= link_to 'Nuevo Proyecto', new_proyect_path, class:"btn btn-primary" %>

p10/app/views/proyects/new.html.erb
<h1>Nuevo Proyecto</h1>

<%= render 'form' %>

<%= link_to 'Regresar', proyects_path, class:"btn btn-success pull-right" %>

p10/app/views/proyects/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <strong>Titulo:</strong>
  <br>
		<div class="container bg-success">
  			<%= @proyect.titulo %>
  	</div>

  <strong>Descripción:</strong>
  <br>
		<div class="container bg-success">
  			<%= @proyect.descripcion %>
  	</div>

</div>

<% if current_user.id == @proyect.user_id %>

<%= link_to 'Editar', edit_proyect_path(@proyect), class:"btn btn-primary pull-left" %>
<%= link_to 'Regresar', proyects_path, class:"btn btn-success pull-right" %>

<h2>Ver Bmc</h2>
<%= link_to 'Index de Bmcs', proyect_bmcs_path(@proyect), class:"btn btn-primary pull-left" %>

<% else %>

<%= link_to 'Regresar', proyects_path, class:"btn btn-success pull-right" %>

<% end %>