p10/config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :proyects do
    resources :bmcs
    resources :pvs
    resources :tvs
  end

  root 'proyects#index'

end

p10/app/models/bmc.rb
class Bmc < ActiveRecord::Base
  belongs_to :proyect
end

p10/app/controllers/bmcs_controller.rb
class BmcsController < ApplicationController
  before_action :set_bmc, only: [:show, :edit, :update, :destroy]
  before_action :set_proyect

  # GET /bmcs
  # GET /bmcs.json
  def index
    @bmcs = Bmc.where(proyect:@proyect).order(created_at: :desc)
  end

  # GET /bmcs/1
  # GET /bmcs/1.json
  def show
  end

  # GET /bmcs/new
  def new
    @bmc = Bmc.new
  end

  # GET /bmcs/1/edit
  def edit
  end

  # POST /bmcs
  # POST /bmcs.json
  def create
    @bmc = Bmc.new(bmc_params)
    @bmc.proyect = @proyect

    respond_to do |format|
      if @bmc.save
        format.html { redirect_to proyect_bmc_path(@proyect,@bmc), notice: 'Bmc ha sido creado.' }
        format.json { render :show, status: :created, location: @bmc }
      else
        format.html { render :new }
        format.json { render json: @bmc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bmcs/1
  # PATCH/PUT /bmcs/1.json
  def update
    @bmc = Bmc.new(bmc_params)
    @bmc.proyect = @proyect

    respond_to do |format|
      if @bmc.update(bmc_params)
        format.html { redirect_to proyect_bmc_path(@proyect,@bmc), notice: 'Bmc ha sido actualizado.' }
        format.json { render :show, status: :ok, location: @bmc }
      else
        format.html { render :edit }
        format.json { render json: @bmc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bmcs/1
  # DELETE /bmcs/1.json
  def destroy
    @bmc.destroy
    respond_to do |format|
      format.html { redirect_to proyect_bmcs_path(@proyect), notice: 'Bmc ha sido eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyect
      @proyect = Proyect.find(params[:proyect_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_bmc
      @bmc = Bmc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bmc_params
      params.require(:bmc).permit(:problema, :propuesta, :cliente, :proyect_id)
    end
end

p10/app/helpers/bmcs_helper.rb
module BmcsHelper
end

p10/app/views/bmcs/_form.html.erb
<%= form_for([@proyect,@bmc]) do |f| %>
  <% if @bmc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bmc.errors.count, "error") %> prohibited this bmc from being saved:</h2>

      <ul>
      <% @bmc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="field">
    <%= f.label :problema %><br>
    <%= f.text_area :problema, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :propuesta %><br>
    <%= f.text_area :propuesta, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :cliente %><br>
    <%= f.text_area :cliente, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar', class:"btn btn-info btn-lg" %>
  </div>
</div>
<% end %>

p10/app/views/bmcs/edit.html.erb
<h1>Editar Bmc</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', proyect_bmc_path(@proyect,@bmc), class:"btn btn-primary pull-left" %>
<%= link_to 'Regresar', proyect_bmcs_path(@proyect), class:"btn btn-success pull-right" %>

p10/app/views/bmcs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Bmcs</h1>

<div class="container">

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr class="info">
      <th>Problema</th>
      <th>Propuesta de valor</th>
      <th>Cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bmcs.each do |bmc| %>
      <tr>
        <td><%= bmc.problema %></td>
        <td><%= bmc.propuesta %></td>
        <td><%= bmc.cliente %></td>
        <td><%= link_to 'Mostrar', proyect_bmc_path(@proyect,bmc) %></td>
        <td><%= link_to 'Editar', edit_proyect_bmc_path(@proyect,bmc) %></td>
        <td><%= link_to 'Eliminar', [@proyect,bmc], method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<br>

<%= link_to 'Nuevo Bmc', new_proyect_bmc_path(@proyect,@bmc), class:"btn btn-primary" %>

<h2>Ver Proyectos</h2>
<%= link_to 'Regresar a proyectos', proyects_path(@proyect), class:"btn btn-primary" %>

p10/app/views/bmcs/new.html.erb
<h1>Nuevo Bmc</h1>

<%= render 'form' %>

<%= link_to 'Regresar', proyect_bmcs_path(@proyect), class:"btn btn-success pull-right" %>

p10/app/views/bmcs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <strong>Problema:</strong>
  <br>
  <div class="container bg-success">
  	<%= @bmc.problema %>
  </div>

  <strong>Propuesta de  Valor:</strong>
  <br>
  <div class="container bg-success">
  	<%= @bmc.propuesta %>
  </div>

  <strong>Cliente:</strong>
  <br>
  <div class="container bg-success">
  	<%= @bmc.cliente %>
  </div>

</div>

<%= link_to 'Editar', edit_proyect_bmc_path(@proyect,@bmc), class:"btn btn-primary pull-left" %>
<%= link_to 'Regresar', proyect_bmcs_path(@proyect), class:"btn btn-success pull-right" %>

<h2>Ver Pv</h2>
<%= link_to 'Index de Propuesta de Valor', proyect_pvs_path(@proyect), class:"btn btn-primary pull-left" %>