p10/config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :proyects do
    resources :bmcs
    resources :pvs
    resources :tvs
  end

  root 'proyects#index'

end

p10/app/models/pv.rb
class Pv < ActiveRecord::Base
  belongs_to :proyect
end

p10/app/controllers/pvs_controller.rb
class PvsController < ApplicationController
  before_action :set_pv, only: [:show, :edit, :update, :destroy]
  before_action :set_proyect

  # GET /pvs
  # GET /pvs.json
  def index
    @pvs = Pv.where(proyect:@proyect).order(created_at: :desc)
  end

  # GET /pvs/1
  # GET /pvs/1.json
  def show
  end

  # GET /pvs/new
  def new
    @pv = Pv.new
  end

  # GET /pvs/1/edit
  def edit
  end

  # POST /pvs
  # POST /pvs.json
  def create
    @pv = Pv.new(pv_params)
    @pv.proyect = @proyect

    respond_to do |format|
      if @pv.save
        format.html { redirect_to proyect_pv_path(@proyect,@pv), notice: 'Propuesta de Valor ha sido creada.' }
        format.json { render :show, status: :created, location: @pv }
      else
        format.html { render :new }
        format.json { render json: @pv.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pvs/1
  # PATCH/PUT /pvs/1.json
  def update
    @pv = Pv.new(pv_params)
    @pv.proyect = @proyect

    respond_to do |format|
      if @pv.update(pv_params)
        format.html { redirect_to proyect_pv_path(@proyect,@pv), notice: 'Propuesta de Valor ha sido actualizada.' }
        format.json { render :show, status: :ok, location: @pv }
      else
        format.html { render :edit }
        format.json { render json: @pv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pvs/1
  # DELETE /pvs/1.json
  def destroy
    @pv.destroy
    respond_to do |format|
      format.html { redirect_to proyect_pvs_path(@proyect), notice: 'Propuesta de Valor ha sido eliminada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyect
      @proyect = Proyect.find(params[:proyect_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_pv
      @pv = Pv.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pv_params
      params.require(:pv).permit(:productos, :generadores, :eliminadores, :tareas, :ganancias, :frustaciones, :proyect_id)
    end
end

p10/app/helpers/pvs_helper.rb
module PvsHelper
end

p10/app/views/pvs/_form.html.erb
<%= form_for([@proyect,@pv]) do |f| %>
  <% if @pv.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pv.errors.count, "error") %> prohibited this pv from being saved:</h2>

      <ul>
      <% @pv.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
  <h2>Propuesta de Valor</h2>
  <div class="field">
    <%= f.label :productos %><br>
    <%= f.text_area :productos, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :generadores %><br>
    <%= f.text_area :generadores, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :eliminadores %><br>
    <%= f.text_area :eliminadores, class:"form-control" %>
  </div>
  <h2>Segmento de Clientes</h2>
  <div class="field">
    <%= f.label :tareas %><br>
    <%= f.text_area :tareas, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :ganancias %><br>
    <%= f.text_area :ganancias, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :frustaciones %><br>
    <%= f.text_area :frustaciones, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar', class:"btn btn-info btn-lg" %>
  </div>
</div>
<% end %>

p10/app/views/pvs/edit.html.erb
<h1>Editar Propuesta de Valor</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', proyect_pv_path(@proyect,@pv), class:"btn btn-primary pull-left" %>
<%= link_to 'Regresar', proyect_pvs_path(@proyect), class:"btn btn-success pull-right" %>

p10/app/views/pvs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Propuesta de Valor</h1>

<div class="container">

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr class="info">
      <th>Productos</th>
      <th>Generadores</th>
      <th>Eliminadores</th>
      <th>Tareas</th>
      <th>Ganancias</th>
      <th>Frustaciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pvs.each do |pv| %>
      <tr>
        <td><%= pv.productos %></td>
        <td><%= pv.generadores %></td>
        <td><%= pv.eliminadores %></td>
        <td><%= pv.tareas %></td>
        <td><%= pv.ganancias %></td>
        <td><%= pv.frustaciones %></td>
        <td><%= link_to 'Mostrar', proyect_pv_path(@proyect,pv) %></td>
        <td><%= link_to 'Editar', edit_proyect_pv_path(@proyect,pv) %></td>
        <td><%= link_to 'Eliminar', [@proyect,pv], method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<br>

<%= link_to 'Nueva Propuesta de Valor', new_proyect_pv_path(@proyect,@pv), class:"btn btn-primary" %>

<h2>Ver Bmcs</h2>
<%= link_to 'Regresar a Bmcs', proyect_bmcs_path(@proyect), class:"btn btn-primary" %>

p10/app/views/pvs/new.html.erb
<h1>Nueva Propuesta de Valor</h1>

<%= render 'form' %>

<%= link_to 'Regresar', proyect_pvs_path(@proyect), class:"btn btn-success pull-right" %>

p10/app/views/pvs/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Propuesta de Valor</h2>

<div class="container">

  <strong>Productos:</strong>
  <br>
  <div class="container bg-success">
    <%= @pv.productos %>
  </div>

  <strong>Generadores:</strong>
  <br>
  <div class="container bg-success">
    <%= @pv.generadores %>
  </div>

  <strong>Eliminadores:</strong>
  <br>
  <div class="container bg-success">
    <%= @pv.eliminadores %>
  </div>

</div>

<h2>Segmentos de Clientes</h2>

<div class="container">

  <strong>Tareas:</strong>
  <br>
  <div class="container bg-success">
    <%= @pv.tareas %>
  </div>

  <strong>Ganancias:</strong>
  <br>
  <div class="container bg-success">
    <%= @pv.ganancias %>
  </div>

  <strong>Frustaciones:</strong>
  <br>
  <div class="container bg-success">
    <%= @pv.frustaciones %>
  </div>

</div>

<%= link_to 'Editar', edit_proyect_pv_path(@proyect,@pv), class:"btn btn-primary pull-left" %>
<%= link_to 'Regresar', proyect_pvs_path(@proyect), class:"btn btn-success pull-right" %>

<h2>Ver Tv</h2>
<%= link_to 'Index de Tabla de Validaciones', proyect_tvs_path(@proyect), class:"btn btn-primary pull-left" %>